name: my_doctor
description: "AI doctor assistant."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  route_manager: ^2.0.2+1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  # change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true